name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: pip install cpplint==1.6.1
    - run: cpplint --recursive .